### ISSUE TITLE
Action description for deleted images is empty

### ISSUE THREAD

**Issue by zezadas** [adsr/irslackd#100]
**Description**
When a user deletes an image the response is  "ACTION deletes:" instead of being something like,  "ACTION deletes: URL_Of_Image" 
The same happens for deletion of own images.

**Steps to reproduce**
1. start a private conversation
2. other user uploads an image
3.other user deletes the same image
4. observe server reply with "ACTION deletes: "

**Expected behavior**
Server would reply with "ACTION deletes:  https://files.slack.com/files-... .png"

**Client setup**
 - IRC client and version: master#ab64a87908ca1de5cdcb0fd07057e57dbf8f4285

**Comment by adsr** [comment]
Thank you @zezadas
