### ISSUE TITLE
[feature] Allow dotfolder to live under ~/.config

### ISSUE THREAD

**Issue by virtualritz** [adsr/irslackd#101]
I thought when *nix utils started stashing configs in `~/.config`, instead of `~/.foo`, that was a great move towards uncluttering the home folder of dotfiles/folders.
Maybe `irslackd` could support that too? If even only as a build flag?

Aka have a `~/.config/irslackd` folder instead of `~/.irslackd`?

P.S.: on macOS, the correct folder, by OS rules, would actually be `~/Library/Application Support/irslackd`. That could be a platform specific build flag that is aways on for this platform.

**Comment by adsr** [comment]
Hi @virtualritz. You should be able to move the `.irslackd` folder anywhere you'd like, and then specify the locations of the keys using flags:

```
./irslackd --privkey=~/.config/irslackd/pkey.pem --cert=~/.config/irslackd/cert.pem
```

You can also specify a directory when initially creating the keys:
```
./bin/create_tls_key.sh -d ~/.config/irslackd
```
