### ISSUE TITLE
Fix reactions to joins, parts, etc

### ISSUE THREAD

**Issue by adsr** [adsr/irslackd#20]
For example, if personX adds a reaction to personY joining a channel, it is currently translated to `<personX> reacts @ <end_user>: blah` instead of `<personX> reacts @ <personY>: blah`.

**Comment by mlauter** [comment]
This also happens in responses to bot messages, e.g.:
`bot: This is a bot message`
`<personX> reacted with :reactji`

Becomes
`<perxonX> reacts @ <me>: reactji`

**Comment by adsr** [comment]
Fixed by da0610b
