### ISSUE TITLE
URL / link of uploaded files is wrong

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#26]
Example: The URL is https://irslackd.slack.com/files/UAV3JGZ88/FAWJX8UG5/skull.jpeg|Test
not https://irslackd.slack.com/files/UAV3JGZ88/FAWJX8UG5/skull.jpeg for

> @hack5190 uploaded a file: <https://irslackd.slack.com/files/UAV3JGZ88/FAWJX8UG5/skull.jpeg|Test Image>

**Comment by adsr** [comment]
Fixed by 9d685656a772b59ee087b126a39cae845cde80bb. URLs are now formatted like `<http://url> (title)`.
