### ISSUE TITLE
"Channel does not support modes" messages

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#31]
The message "Channel does not support modes" keeps reoccurring in the IRC client server window.

Textual (IRC client) channel windows ignore this.   HexChat (IRC client) channel window displays "[#general] End of WHOIS list" for each joined channel (#general, #test, #water-cooler, etc) of the workspace.

The message can repeat as frequently as every 2 minutes, or not at all.  Sometimes the messages will stop at some point.  Other channels the message is never displayed.

No unusual messages in the console window when this occurs.

**Comment by adsr** [comment]
I think that message is due to this line:

https://github.com/adsr/irslackd/blob/fa6b3c8d552097a4131b301bc9cd6df2322852ee/lib/irslackd.js#L266

I originally added this as an attempt to fix the original HexChat issues but I think we can either send an empty mode response or ignore the mode requests entirely.

**Comment by Hack5190** [comment]
I commented out lines 265-267 as a test.  It stops the messages in the server window.  However it doesn't affect the "[#general] End of WHOIS list" messages in the channel window.

**Comment by adsr** [comment]
Can you pull and test? Should be fixed by https://github.com/adsr/irslackd/commit/67fd49024b4a1f8f35e3737a94dd8c681c4d78c1#diff-8d322e23b644fea01a4d5c7f4b4b9c86R489

**Comment by Hack5190** [comment]
Pulled the new irslackd.js file.  The message "Channel does not support modes" appears in the server window and channel window only at initial connection.  Will monitor to see if the message repeats.

**Comment by Hack5190** [comment]
OPPS: I missed the 2nd change you suggested, after making it the "Channel does not support modes" messages are gone!
