### ISSUE TITLE
Add ability to add/remove reactions, edit/delete messages, start a thread

### ISSUE THREAD

**Issue by adsr** [adsr/irslackd#38]
* Need a way to 'query' last N messages in channel, which should return channel, user, message IDs. Can PRIVMSG a special user, or have client send a custom command (QUOTE), or something else (not NOTICE as IRC spec disallows automatic replies from such messages). Returned list of ids should be a NOTICE from the server.

* Requires keeping last N messages on all channels.

* However we decide to implement 'query', we should also support, edit/delete message, add/remove reaction, start thread, maybe other stuff.

* `s/x/y/` as shortcut for edit last message

**Comment by jcolson** [comment]
yes yes, please - since irc gets disconnected all the time, it's easy to miss messages, a query last N messages would be stellar!

**Comment by adsr** [comment]
A quick attempt at this https://gist.github.com/adsr/db827dc0b9fb4712af451b43a059c0bc

Supports the following:

```
/quote SLACK history #testchan 10
/quote SLACK stat #testchan @1556242959.000400
/quote SLACK search hello
```

It's a bit annoying to type out. Next pass, I'll change it to something like `@slack history` in whatever channel or dm you happen to be in.

**Comment by adsr** [comment]
Most of this functionality was added with 69f6ce850fc6b1d36cd06e5f9eaa4d42458666f3
