### ISSUE TITLE
Add support to LEAVE a channel

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#39]
Textual (and I imagine other IRC clients) require a response to the `PART` command.

The developer of Textual provided this
```
Response is typically the command sent. I send “PART #textual :comment” I get back “PART #textual :comment”
```

This is from Textual's debug log for the `##CompSec` channel on `freenode`

```
<< PART ##CompSec :Hack5190 has gone...
[09:07:51] 

>> @time=2018-06-06T13:07:51.981Z :Hack5190!~Hack5190@unaffiliated/hack5190 PART ##CompSec :"Hack5190 has gone..."
[09:07:55]
```

**Comment by jcolson** [comment]
i second this one please!

**Comment by adsr** [comment]
I have had difficulty reproducing this one as well with WeeChat and HexChat. irslackd already replies to PART commands, for example:

```
irc_in PART #test-issue-39 :Leaving
slack_out conversations.leave { channel: 'CFPPG9UQZ' }
slack_in channel_left { type: 'channel_left',
  channel: 'CFPPG9UQZ',
  actor_id: 'UFRD4RMAT',
  event_ts: '1548622857.000800' }
irc_out :premetetho PART #test-issue-39
```
Maybe Textual needs the message field (`:Leaving`) to recognize the response? If that's the case, can someone try this patch https://gist.github.com/adsr/4f686821333fe24d8fba67f480ef1cc6 and issue a `/part #somechan issue39` from your client? If that works, then I will write a proper fix.

**Comment by jcolson** [comment]
that patch does the trick .. a part actually persists between connections to the server now.

**Comment by jcolson** [comment]
noticing a general issue with multiple apps (znc, quassel) -- looks like mode isn't passing all params expected
2019-01-30 14:06:18 [Warn ] IrcEventMode requires 2 params, got: ("#eng-cloud-vault")
2019-01-30 14:06:19 [Warn ] IrcEventMode requires 2 params, got: ("#eng-cloud-cs")
2019-01-30 14:06:21 [Warn ] IrcEventMode requires 2 params, got: ("#eng-cloud-atp")
2019-01-30 14:06:23 [Warn ] IrcEventMode requires 2 params, got: ("#eng-cloud-sal")
2019-01-30 14:06:25 [Warn ] IrcEventMode requires 2 params, got: ("#eng-cloud-general")
2019-01-30 14:06:28 [Warn ] IrcEventMode requires 2 params, got: ("#eng-cloud-release")
2019-01-30 14:06:30 [Warn ] IrcEventMode requires 2 params, got: ("#eng-dublin-social")

**Comment by adsr** [comment]
Re: `MODE` issues, it seems related to commit e15ddb5939753a5206a44caff2a1720a12402d19. There's no Slack equivalent for most `MODE` commands so originally I was just returning an error `ERR_NOCHANMODES` (i.e., `Channel doesn't support modes`) to the client. However it seemed some clients didn't support that. WeeChat by itself seems to handle the 'blank' channel mode response. I don't use a bouncer so I suspect that adds to the complexity here. You might try the patch below which simply echoes back all channel `MODE` commands.

```diff
diff --git a/lib/irslackd.js b/lib/irslackd.js
index 70dab8c..a1bb75c 100644
--- a/lib/irslackd.js
+++ b/lib/irslackd.js
@@ -304,7 +304,7 @@ class Irslackd {
   async onIrcMode(ircUser, msg) {
     let target = msg.args[0];
     if (target.substr(0, 1) === '#') {
-      this.ircd.write(ircUser.socket, 'irslackd', 'MODE', [ target ]);
+      this.ircd.write(ircUser.socket, 'irslackd', 'MODE', msg.args);
     }
   }
   async onIrcList(ircUser, msg) {
```

Re: `PART`, if the patch I linked above does not work then I'm currently out of ideas. If you can paste a copy of the log output (irc_in, irc_out, slack_in, slack_out lines etc) it may help.

**Comment by adsr** [comment]
Please re-open if not resolved. Thank you.
