### ISSUE TITLE
Mute SLACK items such as "reacts @"  and "unreacts @" from being sent to an IRC client

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#42]
Slack sends information used in their clients & web interface, but that info is not useful in IRC.  This information should be muted and not forwarded to the IRC client.  The user name associated with these messages is unique - in Textual it begins with a dot and begins with an asterisk in HexChat.

Examples of these items in IRC (Textual client) are shown here - https://postimg.cc/image/jhv3ie19j/

The same items shown in Slacks web client - https://postimg.cc/image/ydtmq3upj/

**Comment by adsr** [comment]
Hey there @Hack5190. I added the react/unreact messages intentionally. They are not directly from the Slack API. They will hopefully be more useful with #38. But also I will make a note to include an option to disable them entirely (#34).

**Comment by Hack5190** [comment]
Understood, thanks.  FYI: I added a patch to lib/ircd.js in my fork as a temporary fix.

**Comment by adsr** [comment]
Added in 20d7bc6
