### ISSUE TITLE
Frequent "WebSocket is not open Errors"

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#44]
Updated to latest release today - since then frequent errors

> [ERROR] @slack/client:RTMClient failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING)
[ERROR] @slack/client:KeepAlive Unhandled error: Failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING). Please report to @slack/client package maintainers.

Here is a sample of the frequency for this issue

> [13:03:30] *status Connected!
[13:10:43] *status Connected!
[13:15:26] *status Connected!
[13:15:49] *status Connected!
[13:18:10] *status Connected!
[13:21:22] *status Connected!
[13:22:30] *status Connected!
[13:22:42] *status Connected!
[13:27:58] *status Connected!
[13:28:54] *status Disconnected from IRC. Reconnecting...
[13:28:54] *status Connection Refused.  Reconnecting...
[13:30:28] *status Connected!
[13:44:11] *status Connected!
[13:44:48] *status Connected!
[13:44:53] *status Disconnected from IRC. Reconnecting...
[13:44:53] *status Connection Refused.  Reconnecting...
[13:46:26] *status Connected!
[13:47:14] *status Connected!

FYI: ZNC is also running on this system and has no connectivity issues.

**Comment by Hack5190** [comment]
UPDATE: Had to switch back to the previous code release.  This version was consuming so many system resources that it wasn't possible to login - required a hard reset.

**Comment by adsr** [comment]
All of Slack was down for several hours today. Possibly related.

https://status.slack.com/2018-06-27

**Comment by adsr** [comment]
I think the bits for extra stacktrace context[0] is eating a lot of resources. I haven't been able to reproduce #41 since commenting that out. I will revert it.

https://github.com/adsr/irslackd/blob/master/bin/irslackd.js#L4-L6

**Comment by Hack5190** [comment]
The "RTMClient fail" could be related to the outage - they started before Slack reported it.

Switched to the current code release with the lines in bin/irslackd.js removed.

**Comment by Hack5190** [comment]
Sadly it just happened again w/the current code base.  irslackd was connected to 2 workspaces and that matches the errors.

> [ERROR] @slack/client:RTMClient failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING)
[ERROR] @slack/client:RTMClient failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING)
[ERROR] @slack/client:KeepAlive Unhandled error: Failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING). Please report to @slack/client package maintainers.
[ERROR] @slack/client:KeepAlive Unhandled error: Failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING). Please report to @slack/client package maintainers.

**Comment by Hack5190** [comment]
This seems to have gone away w/yesterdays updates.  However now the following is happening frequently.

> slack_in manual_presence_change { type: 'manual_presence_change',
  presence: 'active',
  event_ts: '1530549053.000151' }
slack_out: refreshUsers
slack_out users.list { limit: 1000 }
slack_out usergroups.list { include_count: false,
  include_disabled: false,
  include_users: false,
  limit: 1000 }
slack_out: refreshChannels
slack_out conversations.list { types: 'public_channel,private_channel,mpim', limit: 1000 }
slack_out: hydrateChannel random
slack_out conversations.members { channel: 'C9QTYHTLH', limit: 1000 }
slack_out: hydrateChannel general
slack_out conversations.members { channel: 'C9RBY2S4B', limit: 1000 }
irc_out: joinChannel #random
irc_out :hack5190 JOIN #random
irc_out :irslackd 332 hack5190 #random :Non-work banter and water cooler conversation
irc_out :irslackd 353 hack5190 = #random :hack5190 as_2 as as_3 hack5190
irc_out :irslackd MODE #random
irc_in MODE #random
irc_out :irslackd MODE #random
irc_in MODE #random
irc_out: joinChannel #general
irc_out :hack5190 JOIN #general
irc_out :irslackd 332 hack5190 #general :Channel for Testing, Developing and Support of irslackd - https://github.com/adsr/irslackd

This causes status messages to be sent to the client and seems to occur more frequently the longer irslackd is running.

**Comment by adsr** [comment]
Closing stale issues. Feel free to re-open if needed.
