### ISSUE TITLE
No incoming messages

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#45]
After irslackd has been running for a day or more incoming messages from slack stop.  Outgoing messages continue to work and there are no errors in the irslackd window.

Is this possibly related to issue #44 ?

**Comment by Hack5190** [comment]
Next time this happens I'll run all tests (npm test).  Is there a single test (npm test test_???) that I would help diag this?

**Comment by adsr** [comment]
No incoming messages indicates a problem with the Real-Time Messaging (RTM) client. If you're seeing log output like `WebSocket is not open` such as in #44, that for sure explains it. Outgoing messages are sent separately via the Web API so it's possible you can send without being able to receive.

I just pushed 5b738ac which upgrades the Slack client to the latest version `v4.3.1`. We were 2 versions behind. Looks like they fixed a few RTM bugs. Maybe one of those will fix your issue? Running `npm install` after refreshing the repo should upgrade you.

If it persists after upgrading I'll see if I can reproduce by killing the socket manually via debugger. Maybe there's a way to catch the connection error and restart the RTM client at that point.

**Comment by Hack5190** [comment]
Thanks for the info - I'll monitor and update the status.

**Comment by Hack5190** [comment]
This appears to be resolved.

**Comment by Hack5190** [comment]
It's back :(  -  irslackd has been up for over 3 days w/3 workspaces.  Today 1 of the 3 stopped receiving (forwarding ?) incoming messages to ZNC.  After disconnecting and re-connecting ZNC to irslackd incoming messages started working.

**Comment by cbirkett** [comment]
This happened to me today, but only on two of three Slacks I was connected to. No incoming messages, but outgoing messages went through fine. I checked the terminal and there were no errors. Reconnecting my IRC client to the dead Slacks fixed the issue.

**Comment by adsr** [comment]
Thanks for the reports. I tried reproducing this by attaching to the process with gdb and manually killing the socket associated with the RTM client. Unfortunately that did not reproduce the behavior. It reconnected successfully. So something else is going on.

I added a few things that might help us track down what is happening. Once you update to the latest version (`git pull --rebase && npm install`), please try the following:

1. Run irslackd with RTM client log level set to debug: `./irslackd -L debug ...`. (Replace `...` with whatever options you normally use.) Maybe the debug logs will illuminate what is going on inside the RTM client.

2. It is also convenient to tee output to a log file like: `./irslackd -L debug ... 2>&1 | tee -a irslackd.log`. This way you don't have to worry about copy-pasting output from your terminal, or running out of scrollback buffer.

3. Once connected, `/join +irslackd`, the special debug channel. You can make this happen automatically by appending a space and `debug-chan` to Slack token in your IRC client config.

4. If / when incoming messages stop flowing, switch to the debug channel (`/join +irslackd`) and send the following lines: `dump_server`, `dump_rtm`, `dump_user`. This will cause irslackd to dump internal program state to stdout. If you're teeing logs as suggested in bullet 2 above, the debug output will then be in `irslackd.log`. If not, you can find the output in your terminal where you ran irslackd from. The log lines will likely contain sensitive info so please do not share it without redacting tokens, user names, channel names, chat lines, etc. If there's anything interesting, you can email the relevant parts of the log to me, or post it here if it's sufficiently redacted.

Thanks again.

**Comment by cbirkett** [comment]
It happened again today but unfortunately I'd forgotten to set the debug option last time I ran it, so there was nothing to show.

**Comment by Hack5190** [comment]
After the last instance of this issue, I switched from using _xoxp_ tokens to _xoxs_ tokens and the problem hasn't resurfaced (yet).

**Comment by cbirkett** [comment]
I changed all my tokens but it happened again this afternoon. I have the logs of the dump commands if @adsr would like to sort out how I can send them privately.

**Comment by adsr** [comment]
@cbirkett Thanks. Can you send the logs to as@php.net? Feel free to encrypt if you'd like. Public key is here: https://gist.github.com/adsr/3be56e90a57d93117b1f927f5dae2ce1

**Comment by ta** [comment]
Just to add an observation. My instance had been running for months without displaying the issue, but it began doing exactly this after Slack's operational issues earlier today.

**Comment by adsr** [comment]
Closing stale issues. Feel free to re-open if needed.
