### ISSUE TITLE
Very slow (long) delay in joining channels w/large # of users

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#51]
One of my workspaces is very large in number of channels and number of users in each channel.  By default my ZNC bouncer only connects to two channels.  One channel has 18,993 users and the other 2,746 users.

The smaller channel takes up to 5 minutes to populate and the larger can take 15 to 20 minutes.  Monitoring the output of irslackd in the starting terminal window, messages from these two channels can be seen.

This behavior is reproducible when connecting the IRC client (textual) direct to irslackd - bypassing ZNC.

**Comment by Hack5190** [comment]
UPDATE: After doing some testing, increasing the default setting of 1000 users in lib/slack-refresh.js to 1500 _and_ reducing the same setting in lib/irslackd.js from 1000 to 500 load time has **dramatically** been reduced to ~90 seconds per channel.  

The change doesn't appear to have impacted the load time of channels with (much) smaller user counts in other workspaces.  Further updates will be posted after a few reboots and restarts.

**Comment by adsr** [comment]
Closing stale issues. Feel free to re-open if needed.

**Comment by Hack5190** [comment]
This problem has continued in each release and has been getting worse.  The delay until a channel is populated / accessible can be up to 30 mins.

The group has 861 channels.  I join 2 channels.  The 1st has 31,995 users and the 2nd has 4,490 users.

**Comment by adsr** [comment]
Hey @Hack5190 thanks for the report and hope you're doing well. Can you remind me which Slack workspace this is for? I'd like to join it and attempt reproducing if possible.

**Comment by Hack5190** [comment]
The workspace is MacAdmins.  Doing good, it's been a long time since we chatted.

**Comment by adsr** [comment]
Going to close this as stale. @Hack5190 or anyone else, please feel free to reopen if it's still a problem.
