### ISSUE TITLE
Handle multiple client connections for sent messages

### ISSUE THREAD

**Issue by jcolson** [adsr/irslackd#54]
I've noticed that when connected via machine A and send chat, connected machine B doesn't see my username's chat in room or group chat.

**Comment by adsr** [comment]
Hello, thanks for filing an issue. I had trouble reproducing the issue if I'm understanding it correctly. I connected two separate irc clients (both WeeChat) with the same Slack token to an irslackd instance and then sent messages from both clients. It seemed to work correctly. Client A and B both had a consistent view of the chat. Can you provide more info about your setup? Thank you.

**Comment by jcolson** [comment]
it may be related to one of my clients ("IRC for Android" https://play.google.com/store/apps/details?id=com.countercultured.irc4android ). 

It looks as though any text from myself on Textual does not show up on "IRC for Android".  But the inverse _does_ work.  I see text from "IRC for Android" in my Textual client.  Odd one.

**Comment by adsr** [comment]
My guess is that irc4android is filtering out incoming `PRIVMSG`s that match the local nick, perhaps as a way to handle the `echo-message` extension https://ircv3.net/specs/extensions/echo-message-3.2.html

**Comment by jcolson** [comment]
also, any direct messages to me from others don't show 'unread' count in the query.  is that to be expected?

**Comment by adsr** [comment]
> I did also notice that any messages I send from the official slack client directly to an individual, don't show up in IRC.

Is this just in irc4android or Textual as well? (This works for me in WeeChat.)

> also, any direct messages to me from others don't show 'unread' count in the query. is that to be expected?

There's an api call for marking a message as read which we are not calling from irslackd. Not sure if that is related to what you're describing but it's something that affects unread count off the top of my head. Can you clarify or enumerate steps to reproduce? Thanks.

**Comment by jcolson** [comment]
> Is this just in irc4android or Textual as well? (This works for me in WeeChat.)
Textual is actually where i noticed this.

> There's an api call for marking a message as read which we are not calling from irslackd. Not sure if that is related to what you're describing but it's something that affects unread count off the top of my head. Can you clarify or enumerate steps to reproduce? Thanks.
launch textual - connect to irslackd as user A
launch slack client as user B
send a drect message from slack client user B to user A
the message is received in textual, however no indicator that a new message arrived exists

**Comment by adsr** [comment]
> the message is received in textual, however no indicator that a new message arrived exists

To clarify, the indicator you mention is a feature in Textual? If that is correct I can't think of a reason why Textual would behave differently in this case. Unfortunately I don't have access to a Mac otherwise I would test with Textual myself. Presently I test with WeeChat and HexChat. I will see if I can borrow a Mac from someone next week. In the mean time if you can find a Linux client that exhibits the same problem that would help.

**Comment by jcolson** [comment]
indeed, i tested out weechat, and the query gets 'notified' (turns red) when i receive a new message ... unfortunately Textual still does not (should get an unread count indicator).

**Comment by jcolson** [comment]
Not using textual any longer, so closing as can't verify
