### ISSUE TITLE
too few arguments received from IRC server for command "mode" - connecting to ZNC

### ISSUE THREAD

**Issue by jcolson** [adsr/irslackd#55]
i placed znc in between weechat and irslackd, now I receive the following greetings upon connecting to ZNC ... not sure if this is an issue with MODE response from irslackd?

> 09:58 =!= gnutls: peer's certificate issuer is unknown
> 09:58 -- irc: connected to karma.net/6697 (34.237.248.202)
> 09:58 -- irslackd
> 09:58 -- MOTD blocked by ZNC
> 09:59 -- *status (znc@znc.in): You've connected to ZNC!
> 09:59 =!= irc: too few arguments received from IRC server for command "mode" (received: 3 arguments, expected: at least 4)
> 09:59 =!= irc: failed to parse command "MODE" (please report to developers):
> 09:59 =!= :irslackd MODE #a-team-slackers
> 09:59 =!= irc: too few arguments received from IRC server for command "mode" (received: 3 arguments, expected: at least 4)
> 09:59 =!= irc: failed to parse command "MODE" (please report to developers):
> 09:59 =!= :irslackd MODE #amazon-fuse
> 09:59 =!= irc: too few arguments received from IRC server for command "mode" (received: 3 arguments, expected: at least 4)
> 09:59 =!= irc: failed to parse command "MODE" (please report to developers):
> 09:59 =!= :irslackd MODE #architecture
> 09:59 =!= irc: too few arguments received from IRC server for command "mode" (received: 3 arguments, expected: at least 4)
> 09:59 =!= irc: failed to parse command "MODE" (please report to developers):
> 09:59 =!= :irslackd MODE #blhgt-2fa

**Comment by adsr** [comment]
Re: `MODE` issues, it seems related to commit e15ddb5939753a5206a44caff2a1720a12402d19. There's no Slack equivalent for most `MODE` commands so originally I was just returning an error `ERR_NOCHANMODES` (i.e., `Channel doesn't support modes`) to the client. However it seemed some clients didn't support that. WeeChat by itself seems to handle the 'blank' channel mode response. I don't use a bouncer so I suspect that adds to the complexity here. You might try the patch below which simply echoes back all channel `MODE` commands.

```diff
diff --git a/lib/irslackd.js b/lib/irslackd.js
index 70dab8c..a1bb75c 100644
--- a/lib/irslackd.js
+++ b/lib/irslackd.js
@@ -304,7 +304,7 @@ class Irslackd {
   async onIrcMode(ircUser, msg) {
     let target = msg.args[0];
     if (target.substr(0, 1) === '#') {
-      this.ircd.write(ircUser.socket, 'irslackd', 'MODE', [ target ]);
+      this.ircd.write(ircUser.socket, 'irslackd', 'MODE', msg.args);
     }
   }
   async onIrcList(ircUser, msg) {
```

**Comment by jcolson** [comment]
patch applied ... playing with quassel now, and not seeing the MODE issue now.  (btw quassel and it's android app are an amazing layer on top!)

**Comment by adsr** [comment]
@jcolson Re: the patch above, does it also fix your issue if you use `[target, '']` instead of `msg.args`?

**Comment by jcolson** [comment]
yes, i believe that did the trick, as i have not seen the MODE issue messages any longer

**Comment by jcolson** [comment]
I fixed this by returning if args wasn't large enough
