### ISSUE TITLE
/away by itself doesn't send the slack instance an 'active presence'

### ISSUE THREAD

**Issue by jcolson** [adsr/irslackd#56]
/away with a message works as expected.

/away with no message doesn't set your presence to active in the slack instance, as it should.

/back doesn't seem to clear it either

**Comment by plantroon** [comment]
I couldn't find any documentation on how to make Irslackd appear as if I am online or away. I also get a lot of "has joined" messages.

What I would like it to do is always tell that I am online. I don't even need the away functionality, but people keep telling me that I appear offline all the time as I don't use the /away command on IRC. Is this possible?

(Sorry if hijacking but this is related to away functionality)

**Comment by adsr** [comment]
@jcolson @plantroon I created a bug report template if you don't mind refiling the issues with more info (log output, client versions, etc). Thanks.

**Comment by plantroon** [comment]
Actually this might not be possible via any standard Slack API. Only be reconnecting every now and then am I able to achieve always-online presence. I do not think this is a bug in irslackd, but rather Slack's limited API. Slack will auto-away you after some time. Nothing other than reconnecting helps.

There is a ruby gem dedicated to this functionality: slack-keep-presence -v 0.1.9

**Comment by pbui** [comment]
@plantroon I believe enabling the `typing-notifications` configuration will help keep your presence active.  I have that and the `presence` features enabled and I am usually kept active.

**Comment by plantroon** [comment]
Thanks for the suggestion but it didn't work. What I resorted to doing is restarting irslackd itself with a cronjob (weechat automatically reconnects) to keep online presence. That way I have control on when I appear online. I don't use this to "cheat" the online status, I just do not want to open the Slack client every time I start a work day. I run on underpowered libreboot hardware (by choice) and the Slack client eats more resources than the rest of my system lol.

**Comment by jcolson** [comment]
@plantroon - you may try https://github.com/rockymadden/homebrew-rockymadden/blob/master/Formula/slack-cli.rb as a cronjob to just set the presence... seems to work ok for me ...  i use it to set my current location (status) and then hit the presence api.  i just have it cron'd every hour.

**Comment by adsr** [comment]
Slack documentation indicate that making any API calls should maintain presence in 30 minute intervals if the user is in `auto` mode (which irslackd sets).

https://api.slack.com/docs/presence-and-status#automatic_away

I also haven't been able to reproduce this one personally. Going to close this for now.
