### ISSUE TITLE
Private channels do not respond to renames properly

### ISSUE THREAD

**Issue by jcolson** [adsr/irslackd#68]
**Description**
when a channel is renamed, it does not get renamed in irslackd

**Steps to reproduce**
1. ... create channel in slack
2. ... rename channel in slack
3. ... note that channel is not renamed in irslackd

**Expected behavior**
channel should be renamed

**Comment by jcolson** [comment]
hmmm ... i lie ... it looks like maybe it just takes a little bit?  closing for now

**Comment by jcolson** [comment]
it looks like this happens for private channels

**Comment by adsr** [comment]
Tracking here https://github.com/adsr/irslackd/issues/75
