### ISSUE TITLE
3 vulns with eslint/lodash on fresh npm install

### ISSUE THREAD

**Issue by tatmantech** [adsr/irslackd#70]
Working with 5.15.1 eslint in package.json. npm install fails as per readme due to dev vuln. I know it's just for linting dev...

output of npm audit in nodeenv iso environment:

Run  npm install --save-dev eslint@5.15.1  to resolve 3 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬─────────┐
│ Moderate      │ Prototype Pollution                                  │
├───────────────┼─────────┤
│ Package       │ lodash                                                       │
├───────────────┼─────────┤
│ Dependency of │ eslint [dev]                                          │
├───────────────┼─────────┤
│ Path          │ eslint > inquirer > lodash                            │
├───────────────┼─────────┤
│ More info     │ https://npmjs.com/advisories/782          │
└───────────────┴─────────┘

┌───────────────┬─────────┐
│ Moderate      │ Prototype Pollution                                  │
├───────────────┼─────────┤
│ Package       │ lodash                                                       │
├───────────────┼─────────┤
│ Dependency of │ eslint [dev]                                          │
├───────────────┼─────────┤
│ Path          │ eslint > lodash                                              │
├───────────────┼─────────┤
│ More info     │ https://npmjs.com/advisories/782          │
└───────────────┴─────────┘

┌───────────────┬─────────┐
│ Moderate      │ Prototype Pollution                                 │
├───────────────┼─────────┤
│ Package       │ lodash                                                       │
├───────────────┼─────────┤
│ Dependency of │ eslint [dev]                                          │
├───────────────┼─────────┤
│ Path          │ eslint > table > lodash                                 │
├───────────────┼─────────┤
│ More info     │ https://npmjs.com/advisories/782          │
└───────────────┴─────────┘

found 3 moderate severity vulnerabilities in 374 scanned packages
  3 vulnerabilities require semver-major dependency updates.

**Comment by adsr** [comment]
Please re-open if not resolved. Thank you.
