### ISSUE TITLE
Very long joining slack with many channels

### ISSUE THREAD

**Issue by afish** [adsr/irslackd#71]
I have a Slack workspace with almost 400 channels and joining it takes around 20 minutes. I verified that by looking into logs and by sending some message to a channel — it was actually delivered to Slack after ~20 minutes.

Is there a way to speed things up? I am using ZNC as well but this doesn't help, when I connect with new client to ZNC I still need to wait a long time.

**Comment by adsr** [comment]
Thanks for the report @afish. Can you provide more details of your setup? CPU, RAM, bandwidth, operating system and version, IRC client and version, irslackd logs if possible. Also if you can send an invite to your Slack workspace that would help.

@Hack5190 had similar troubles with long starts in the past. I was never able to reproduce it unfortunately. For comparison sake, the Slack workspace I use daily has many thousands of channels and users. Connecting finishes in a few seconds.

**Comment by afish** [comment]
I am hosting this on Azure VM of size B2s, 2 VCPUs, 4 GB RAM, 1600 IOPS, some decent network (100 Mbps or 1 Gbps, not sure). I am using two Docker containers on that machine, one of them is ZNC which is exposed on port 6697 and connects to irslackd using localhost:6687 with SSL.

Irslackd is in container with this dockerfile:

```
FROM fedora:latest

RUN yum -y install libtool-ltdl libnsl libstdc++ ncurses npm && \
    yum -y install wget hostname findutils telnet git npm && \
    yum -y install procps-ng net-tools && \
    yum -y update && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN useradd irslackduser

RUN cd /home/irslackduser && \
	git clone https://github.com/adsr/irslackd.git && \
        cd irslackd && \
        npm install

EXPOSE 6687:6687

VOLUME /root/.irslackd

CMD ["/home/irslackduser/irslackd/./irslackd", "-p", "6687", "-a", "0.0.0.0"]
```

If you are not familiar with docker, then in short: I create new container using Fedora image, install some dependencies, create new user directory, clone irslackd repository and install dependencies. Container runs irslackd with -p and -a parameters. Certificates were generated previously and are mounted from host so they persist when container is dropped and recreated.

I can't invite you to the workspace, though. It is a free workspace, created something like a year ago, it has 352 channels. Please find log attached. It has personal details stripped.
[log.txt](https://github.com/adsr/irslackd/files/3021238/log.txt)
I started container and enabled ZNC to connect to it, then I used kiwiirc.com to connect to ZNC.

```
21:03 ZNC started
21:03 kiwiirc.com started
21:06 I see my user joining a channel (reported by kiwiirc). I am sending message "21:06".
21:08 I see my user joining the same channel again. I am sending message "21:08".
21:16 I noticed kiwiirc.com was disconnected. I reconnect, join channel, send message "21:16".
21:22 Disconnected again, rejoin, send "21:22".
21:31 Disconnected again, rejoin, send "21:32".
21:38 Disconnected. I don't reconnect.
21:42 Message "21:06" finally appears in Slack.
21:55 I reconnect and send message "21:56".
21:58 Message "21:08" finally appears in slack".
22:03 stopped service
```

So this time it is even slower then it was earlier.

top on host shows that I have plenty of computer power.
(s):  0.2 us,  0.3 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4028540 total,  2443860 free,   391792 used,  1192888 buff/cache

I had similar issues with Matterircd, maybe it is not a problem in this software but in Slack workspace?

I may be out for next few days so please expect delay in my responses.

**Comment by adsr** [comment]
Please re-open if not resolved. Thank you.
