### ISSUE TITLE
Authentication question

### ISSUE THREAD

**Issue by MaxLeiter** [adsr/irslackd#76]
What do I use as my nickname for authentication? The wiki just says workspace name; I'm not sure what that means. My "full name" has a space and I login using my email. Trying to use my email as my nick did not work. Thanks for any help

**Comment by adsr** [comment]
Hi @MaxLeiter. You can set your IRC nick to anything. The important part for auth is that your client sends a `PASS` command containing an `xoxp-` access token. irslackd should automatically admin-`NICK` your client to the correct Slack username associated with your access token. If that's not working please file a bug. Thanks!
