### ISSUE TITLE
Failing to connect, please help

### ISSUE THREAD

**Issue by dmitriz** [adsr/irslackd#79]
**Description**

I have been trying to follow all the instructions as exactly as I could but somehow still fail to connect.

I am using XChat Azure 1.16.1 (1.16.1) downloaded from
https://github.com/xchataqua/downloads

**Steps to reproduce**
Following https://github.com/adsr/irslackd#setup, Step 6, I enter in the XChat Azure CLI:

Enter `/server add irslackd_workspace localhost/6697`
Resp: `Looking up add. Unknown host. Maybe you misspelled it?`

Other tries, no success :

Enter `/server`
Resp: `Usage: SERVER [-ssl] <host> [<port>] [<password>], connects to a server, the default port is 6667 for normal connections, and 9999 for ssl connections`

Enter `/server localhost 6697`
Resp: 
```sh
Looking up localhost
 * Connecting to localhost (::1) port 6697...
 * Connected. Now logging in...
 * Disconnected (Remote host closed socket).
```

Enter `/server -ssl localhost 6697`
Resp:
```sh
Looking up localhost
 * Connecting to localhost (127.0.0.1) port 6697...
 * Connection failed. Error: (336151568) error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
```

**Expected behavior**
Connect or getting more helpful error messages 

**Log output**
No output in the terminal console where `irslackd` is running.

**Client setup**
 - IRC client and version: XChat Azure 1.16.1 (1.16.1)
 - IRC bouncer and version (if any): No
 - OS: Mac OSX 10.8.5

**Comment by adsr** [comment]
Thanks for the report @dmitriz. I don't have a Mac to test that client unfortunately. However I can offer a few tips.

1. Is there any output from irslackd itself?

2. It looks like there was a TLS error. You might try running irslackd with the `-i` flag to disable TLS and then using `/server` without `-ssl`.

3. Going by your client's help output for `/server`, you might try `/server localhost <port> <slack-token>`.

**Comment by dmitriz** [comment]
> It looks like there was a TLS error. You might try running irslackd with the -i flag to disable TLS and then using /server without -ssl.

I have enventually managed to connect with `-i` flag, thank you for the hint!

What I still cannot do is entering threads or private channels, appreciate any suggestion where to look for more info here.

**Comment by adsr** [comment]
Hello @dmitriz Can you file a separate bug report if this is still not working for you? Thank you.
