### ISSUE TITLE
Investigate xoxc Authorization header

### ISSUE THREAD

**Issue by adsr** [adsr/irslackd#91]
See @ltworf's comment https://github.com/adsr/irslackd/issues/84#issuecomment-591879982

**Comment by Hack5190** [comment]
This is how I get an xoxc token to work (hope it helps) . . . . .

1) log into workspace (I use FireFox)
2) open 'web developer' - 'network'
3) select a 'POST' or 'GET' who's domain is the same as the workspace name
4) select 'Cookies' and copy the d value
5) select 'Params' and copy the xoxc value
6) base64 the cookie - include (or add if not present) "d=" at the start and ";" at the end
7) token format is <xoxc-token>|<base64-cookie>

NOTE: use the xoxc and d values from _the same_ POST or GET.

**Comment by ltworf** [comment]
On my README I have documented how to get it.

https://github.com/ltworf/localslackirc/blob/master/README.md#obtain-a-slack-cookie

The annoying thing is that it's a special kind of cookie that isn't available to js, so one can't just instruct to copy paste some js to get it.

Inspecting the cookies works as well but since all browsers are different, it is a bit of an hassle to try and find them.

**Comment by Hack5190** [comment]
> On my README I have documented how to get it.
> 
> https://github.com/ltworf/localslackirc/blob/master/README.md#obtain-a-slack-cookie
> 
> The annoying thing is that it's a special kind of cookie that isn't available to js, so one can't just instruct to copy paste some js to get it.
> 
> Inspecting the cookies works as well but since all browsers are different, it is a bit of an hassle to try and find them.

Hey ltworf, been a long time since we chatted!

Couldn't agree more that finding the needed items to make this work is different in every browser.  You and pigmej mentioned in issue #84 that Adam's directions in the guide didn't work.  They didn't work for me either so I wanted to share a process that worked for me in the hopes that others would try it and hopefully benefit.

**Comment by fancypantalons** [comment]
Just a heads up:  Hexchat has (inexplicably) a hardcoded password length limit of 85-ish characters, which makes using the xoxc auth header break...

**Comment by adsr** [comment]
Here's an easier way to get the xoxc token (at the cost of brittleness). Paste the code below into your browser's javascript console and hit enter. Seems to work on all my Slack workspaces. Tested in latest Chrome.

```js
console.log((function() {
  // get workspace_id
  var workspace_match = location.href.match(/(?<=\/client\/).+?(?=\/)/g);
  if (!workspace_match) return "Error: Expected `/client/.../` in URL";
  var workspace_id = workspace_match[0];

  // parse localConfig_v2
  if (!localStorage || !localStorage.localConfig_v2) return "Error: Expected localStorage.localConfig_v2";
  var slack_cfg = JSON.parse(localStorage.localConfig_v2);
  if (!slack_cfg) return "Error: Could not parse localStorage.localConfig_v2";

  // get token in localConfig_v2
  if (!slack_cfg.teams) return "Error: Expected localConfig_v2.teams";
  if (!slack_cfg.teams[workspace_id]) return "Error: Expected teams[workspace_id]";
  if (!slack_cfg.teams[workspace_id].token) return "Error: Expected teams[workspace_id].token";

  return "Token:\n\n" + slack_cfg.teams[workspace_id].token + "\n\n";
})());
```

The auth cookie `d` is marked `HttpOnly` so it's unfortunately not accessible to js via `document.cookie`. Probably the only way we'll have a 1-click solution for end-users is to write a browser extension or a script that prompts the end-user for their credentials.

**Comment by fancypantalons** [comment]
FYI, that regex contains lookbehinds, which only Chrome seems to support (or, at least, Firefox definitely doesn't).  This version of that snippet seems to work across both browsers:

```javascript
  var workspace_match = location.href.match(/\/client\/([^/]+)/);
  if (!workspace_match) return "Error: Expected `/client/.../` in URL";
  var workspace_id = workspace_match[1];
```

It occurred to me, maybe a bookmarklet would work?  This version of your code functions really nicely in a bookmarklet:

```javascript
javascript:(function() {
  var workspace_match = location.href.match(/\/client\/([^/]+)/);
  if (!workspace_match) return "Error: Expected `/client/.../` in URL";
  var workspace_id = workspace_match[1];
  if (!localStorage || !localStorage.localConfig_v2) return "Error: Expected localStorage.localConfig_v2";
  var slack_cfg = JSON.parse(localStorage.localConfig_v2);
  if (!slack_cfg) return "Error: Could not parse localStorage.localConfig_v2";
  if (!slack_cfg.teams) return "Error: Expected localConfig_v2.teams";
  if (!slack_cfg.teams[workspace_id]) return "Error: Expected teams[workspace_id]";
  if (!slack_cfg.teams[workspace_id].token) return "Error: Expected teams[workspace_id].token";
  document.querySelector(".ql-editor > p").append("Token: " + slack_cfg.teams[workspace_id].token);
})();
```

In particular, this version dumps the token out into the Slack input field where it's easy to copy and paste.

Question though:  The output token isn't in the format that irslackd needs (token|base64).  So how would one use this output to get to the correct content for the password?

**Comment by adsr** [comment]
Nice improvement there. Yeah, unfortunately the xoxc token is only half of what we need. We also need the auth cookie which is not accessible via javascript. (It is an `HttpOnly` cookie.) We'd need to either write a browser extension or a program that prompts for the user's credentials to get at that cookie.

**Comment by ltworf** [comment]
Run this javascript code: ```q=JSON.parse(localStorage.localConfig_v2)["teams"]; q[Object.keys(q)[0]]["token"]```

What's wrong with what I wrote in `localslackirc` readme to just get the token?

Anyway as @adsr said, the other cookie is not accessible via javascript. One can click around to see the cookies or one can trigger a request and see the headers in the network traffic. If you do find an alternative way, it's a bad security issue in the browser :)

**Comment by plantroon** [comment]
I tried using the instructions https://github.com/adsr/irslackd/wiki/IRC-Client-Config#xoxc-tokens with multiple workspaces and it did not work. In logs it just says Invalid auth. Is this supposed to work in the current version of irslackd/am I possibly doing anything wrong? Could somebody else test this as well?

By the way, the project https://github.com/wee-slack/wee-slack has xoxc support without the cookie part - perhaps they are doing things differently?

**Comment by adsr** [comment]
Hi @plantroon does it work on the [irslackd workspace](https://irslackd.slack.com/)? I just tested a fresh xoxc token + auth cookie there and it worked.

**Comment by plantroon** [comment]
> Hi @plantroon does it work on the [irslackd workspace](https://irslackd.slack.com/)? I just tested a fresh xoxc token + auth cookie there and it worked.

Yes, that one worked. I tried doing it all over for the other Slack workspace I am trying to connect to (kubernetes.slack.com) and this time it's not working due to rate limiting. But no invalid auth, so I may have been doing something wrong yesterday.

**Comment by plantroon** [comment]
@adsr  not even irslackd Slack channel works for me anymore.

BTW I tried using xoxs-* session tokens (from team.slack.com/customize page, you see boot_data.api_token variable, but it doesn't work anymore) and they work still. But you can't get them anymore apparently.

**Comment by adsr** [comment]
@plantroon Can share output from `bin/token-test.js <token>`?

```
adam@asx1c6:~/irslackd$ bin/token-test.js 'xoxc-...|...'
Using slackToken="xoxc-..."
Using slackCookie="d=...; d-s=..."
Testing slack.WebClient...
Calling: auth.test({})
Calling: users.list({})
Calling: users.list({})
Calling: conversations.list({})
Calling: usergroups.list({})
Calling: conversations.open({"users": "U9RDVNL6P"})
Calling: conversations.close({"channel": "D9RLB2E8M"})
Calling: users.info({"user": "U9RDVNL6P"})
Calling: users.profile.get({"user": "U9RDYK684"})
Calling: users.profile.set({"user": "U9RDYK684", "profile": {"status_text": "test", "status_emoji": ":sunglasses:"}})
Calling: users.profile.set({"user": "U9RDYK684", "profile": {"status_text": "test", "status_emoji": ":sunglasses:"}})
Calling: users.setPresence({"user": "U9RDYK684", "presence": "auto"})
Calling: conversations.join({"channel": "CAG8KJ7LP"})
Calling: conversations.info({"channel": "CAG8KJ7LP"})
Calling: conversations.members({"channel": "CAG8KJ7LP"})
Calling: conversations.leave({"channel": "CAG8KJ7LP"})
Calling: users.info({"user": "UAVGBGY1X"})
Calling: bots.info({"bot": "BAX4BBGVD"})
Testing slack.RTMClient...
Received ready event
Looks OK!
```

I just pushed an update to the script to print out those "Using slackToken" and "Using slackCookie" lines. I want to make sure the cookie includes the `d` value and is formatted correctly (no extra whitespace etc). Feel free to redact the actual values like I did above (`...`) if you post them here, but if anything looks obviously broken or misformatted please make a note.

**Comment by plantroon** [comment]
@adsr thanks for the updates

I took the whole cookie, by right-clicking and pressing Copy value in the web browser, just to be sure I am not missing anything. Then I copied it into terminal and base64 encoded it (as per instructions).

Here's what I get from my testing with irslackd workspace (not sure if this is helpful, it really just says Invalid auth):

```
plantroon@sandbox:~/irslackd$ ./bin/token-test.js 'xoxc-...|...'
Using slackToken="xoxc-..."
Using slackCookie="b=....; shown_ssb_redirect_page=1; shown_download_ssb_modal=1; show_download_ssb_banner=1; no_download_ssb_banner=1; documentation_banner_cookie=1; utm={\"utm_source\":\"in-prod\",\"utm_medium\":\"inprod-customize_link-slack_me\"}; x=...; OptanonAlertBoxClosed=2021-07-21T19:09:04.663Z; OptanonConsent=isIABGlobal=false&datestamp=Wed+Jul+21+2021+21:11:52+GMT+0200+(Central+European+Summer+Time)&version=6.12.0&hosts=&consentId=...&interactionCount=2&landingPath=NotLandingPage&groups=C0004:1,C0002:1,C0003:1,C0001:1&AwaitingReconsent=false&geolocation=SK;BC; d=...+.../..././.../...; d-s=...; lc=..."
Testing slack.WebClient...
Calling: auth.test({})
{ Error: An API error occurred: invalid_auth
    at Object.platformErrorFromResult (/home/plantroon/irslackd/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/home/plantroon/irslackd/node_modules/@slack/web-api/dist/WebClient.js:156:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'slack_webapi_platform_error',
  data: { ok: false, error: 'invalid_auth', response_metadata: {} } }
{ NONE: '{}' }
```


BTW, I retried just now with token-test.js, and irslackd workspace does not work, while kubernetes workspace started working. Maybe try both too? :D I know how ridiculous it sounds.

**Comment by plantroon** [comment]
@adsr OK I think I figured it out. When I use the "Copy value" from the web browser, it formats the text differently from when I just copy it straight away by selecting and copying. So I was doing that wrong all along. TIL.

**Comment by adsr** [comment]
Good find @plantroon. I made a note about that in the wiki. Thanks!

**Comment by orhun** [comment]
> Snippet from the d= value:
> 
>     * Right clicking on the header and clicking Copy value produces data decoded in some way (some html encoding I guess):
> 
> 
> ```
> m57SD3OQbH/g1B/4QRF+P
> ```
> 
>     * Just selecting and copying the header's value produces exactly what's seen in the browser and what works with Irslackd:
> 
> 
> ```
> m57SD3OQbH%2Fg1B%2F4QRF%2BP
> ```

I realized on Firefox, **d=** field is always shown processed (like in the first example: `m57SD3OQbH/g1B/4QRF+P`), regardless of it's been copied via right click or selection. So you have to manually URL encode it to make it work. (`m57SD3OQbH%2Fg1B%2F4QRF%2BP`)

@adsr it'd be nice to mention this in the Wiki as well.

**Comment by adsr** [comment]
Updated. Thank you @orhun.

**Comment by adsr** [comment]
`xoxc` tokens appear to be dead. Don't know of any alternatives. Please file a new issue if you do.
